-- Baseline inferred from the live Hillbilly Deluxe app and one REST row.
-- Keep service-role keys out of browser code and GitHub.

create table if not exists public.parts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  notes text,
  make text default 'Unknown',
  status text default 'Available',
  catalog_group text default 'Unknown',
  part_number text default 'Unknown',
  primary_location text,
  location text,
  photo_url text,
  quantity integer not null default 1 check (quantity > 0),
  garage_area text,
  garage_cabinet text,
  cabinet_shelf text,
  cabinet_bin text,
  large_shelf text,
  storage_shelf text
);

create index if not exists parts_created_at_idx on public.parts (created_at desc);
create index if not exists parts_part_number_idx on public.parts (part_number);
create index if not exists parts_status_idx on public.parts (status);
create index if not exists parts_catalog_group_idx on public.parts (catalog_group);

create table if not exists public.catalog_entries (
  id bigint generated by default as identity primary key,
  source text not null default '1964 Mopar Parts Catalog',
  part_number text,
  part_type_code text,
  group_number text,
  group_name text,
  description text,
  application text,
  year_start integer,
  year_end integer,
  make text,
  model text,
  body_style text,
  pdf_page integer,
  confidence numeric(4,3) default 1,
  created_at timestamptz not null default now()
);

create index if not exists catalog_entries_part_number_idx on public.catalog_entries (part_number);
create index if not exists catalog_entries_group_number_idx on public.catalog_entries (group_number);
create index if not exists catalog_entries_make_model_idx on public.catalog_entries (make, model);

create table if not exists public.part_catalog_matches (
  id bigint generated by default as identity primary key,
  part_id bigint not null references public.parts (id) on delete cascade,
  catalog_entry_id bigint not null references public.catalog_entries (id) on delete cascade,
  match_type text not null,
  confidence numeric(4,3) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  unique (part_id, catalog_entry_id, match_type)
);

create table if not exists public.duplicate_candidates (
  id bigint generated by default as identity primary key,
  part_id bigint not null references public.parts (id) on delete cascade,
  possible_duplicate_part_id bigint not null references public.parts (id) on delete cascade,
  reason text not null,
  confidence numeric(4,3) not null default 0,
  status text not null default 'Open',
  created_at timestamptz not null default now(),
  check (part_id <> possible_duplicate_part_id)
);
